apiVersion: v1
kind: Service
metadata:
    name: jenkins
    namespace: cicd
    annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb    # Use Network Load Balancer
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 50000
      targetPort: 50000
      protocol: TCP
      name: jnlp
    selector:
      app: jenkins
      