---
apiVersion: v1
kind: Service
metadata:
  name: zap-proxy
  namespace: cicd
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 8090
    targetPort: 8090
    protocol: TCP
    name: websocket
  selector:
    app: zap-proxy
