apiVersion: apps/v1
kind: Deployment
metadata:
  name: zap-proxy
  namespace: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zap-proxy
  template:
    metadata:
      labels:
        app: zap-proxy
    spec:
      containers:
      - name: zap-proxy
        image: ghcr.io/zaproxy/zaproxy:stable
        args:
        - "zap.sh"
        - "-daemon"
        - "-host"
        - "0.0.0.0"
        - "-port"
        - "8080"
        - "-config"
        - "api.disablekey=true"
        - "-config"
        - "api.addrs.addr.name=.*"
        - "-config"
        - "api.addrs.addr.regex=true"
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8090
          name: websocket
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "500m"